= structurizr-test
flatrick
v1.0, 2025-03-19
:toc:

== structurizr-test

This repo serves as a test-bed for trying to create a template on how to work with the https://c4model.com/[C4 Model] with the "(Software-)Diagrams-As-Code" language https://docs.structurizr.com/dsl[Structurizr DSL], using the tools https://docs.structurizr.com/lite[structurizr-lite] for actually modelling and https://github.com/avisi-cloud/structurizr-site-generatr[structurizr-site-generatr] for creating the static webpage showcasing the model(s).

=== Setting up the tools

First, you'll need to install a https://adoptium.net/[Java Runtime] _(v17 or newer)_ and https://graphviz.org/download/[GraphViz] as both softwares depend on these. +
It is possible to run these through containers as well, but this readme will focus on running these natively on a Windows-machine for the best possible performance.

==== structurizr-lite

- Download the latest version as a **.war** file from https://github.com/structurizr/lite/releases/latest[structurizr-lite]
- Unpack it where you want to keep it (for the sake of this guide, I'm going to assume that you've put it in `+C:\tools\structurizr-lite\+`)

==== structurizr-site-generatr

- Download the latest version as a **.zip** file from https://github.com/avisi-cloud/structurizr-site-generatr/releases/latest[structurizr-site-generatr]
- Unpack it where you want to keep it (for the sake of this guide, I'm going to assume that you've put it in `+C:\tools\structurizr-site-generatr\+`)